# -*- coding: utf-8 -*-
"""Graficos Cournot e outros.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DupdAtPwI0Hm3wFPnpxQhJR394x0NemF
"""

import matplotlib.pyplot as plt
import numpy as np

# Valor de (a - c)/2b assumido
k = 3

# Pontos para q1 e q2
q = np.linspace(0, 6, 300)

# Curvas de reação
q2_r = k - 0.5 * q  # q2 em função de q1
q1_r = k - 0.5 * q  # q1 em função de q2

# Configurar o gráfico
plt.figure(figsize=(6, 6))

plt.plot(q1_r, q, label=r'$CMR_1$', color='red')
plt.plot(q, q2_r, label=r'$CMR_2$', color='blue')

# Ponto de equilíbrio
plt.plot(2, 2, 'ko')
plt.text(2.1, 1.9, 'Equilíbrio', fontsize=10)

# Interseções com os eixos
plt.plot(0, k, 'bo')
plt.plot(k, 0, 'bo')

# Projeções do equilíbrio nos eixos
plt.plot([2, 2], [0, 2], linestyle=':', color='gray')  # vertical
plt.plot([0, 2], [2, 2], linestyle=':', color='gray')  # horizontal

# Rótulos das projeções
plt.text(2.1, -0.4, r'$q_1^*$', fontsize=11)
plt.text(-0.6, 2.1, r'$q_2^*$', fontsize=11)

# Eixos
plt.axvline(0, color='black', linewidth=0.5)
plt.axhline(0, color='black', linewidth=0.5)

# Rótulos em negrito deslocados
plt.text(6.3, -0.2, r'$\mathbf{q_1}$', fontsize=13)
plt.text(-0.5, 6.3, r'$\mathbf{q_2}$', fontsize=13)

# Título e legenda
plt.title('Curvas de Melhor Resposta  - Modelo de Cournot')
plt.legend()
plt.grid(True)

# Limites e sem números nos eixos
plt.xlim(0, 6.5)
plt.ylim(0, 6.5)
plt.xticks([])
plt.yticks([])

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import numpy as np

# Valor de (a - c)/2b assumido
k = 3

# Pontos para q1 e q2
q = np.linspace(0, 6, 300)

# Curvas de reação
q2_r = k - 0.5 * q  # q2 em função de q1
q1_r = k - 0.5 * q  # q1 em função de q2

# Configurar o gráfico
plt.figure(figsize=(6, 6))

plt.plot(q1_r, q, label=r'$CMR_1$', color='red')
plt.plot(q, q2_r, label=r'$CMR_2$', color='blue')

# Ponto de equilíbrio
plt.plot(2, 2, 'ko')
plt.text(2.1, 1.9, 'Equilíbrio', fontsize=10)

# Interseções com os eixos
plt.plot(0, k, 'bo')
plt.plot(k, 0, 'bo')

# Projeções do equilíbrio nos eixos
plt.plot([2, 2], [0, 2], linestyle=':', color='gray')  # vertical
plt.plot([0, 2], [2, 2], linestyle=':', color='gray')  # horizontal

# Rótulos das projeções
plt.text(2.1, -0.4, r'$q_1^*$', fontsize=11)
plt.text(-0.6, 2.1, r'$q_2^*$', fontsize=11)

# Eixos
plt.axvline(0, color='black', linewidth=0.5)
plt.axhline(0, color='black', linewidth=0.5)

# Rótulos em negrito deslocados
plt.text(6.3, -0.2, r'$\mathbf{q_1}$', fontsize=13)
plt.text(-0.5, 6.3, r'$\mathbf{q_2}$', fontsize=13)

# Título e legenda
plt.title('Curvas de Melhor Resposta  - Modelo de Cournot')
plt.legend()
plt.grid(True)

# Limites e sem números nos eixos
plt.xlim(0, 6.5)
plt.ylim(0, 6.5)
plt.xticks([])
plt.yticks([])

plt.tight_layout()
plt.show()

